# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"

# Added at 2017-07-11 17:24:19 +0000 by root:
gem "ruby-debug-ide", "= 0.4.32"

# Added at 2017-07-11 17:25:14 +0000 by root:
gem "debase", "= 0.2.1"
